export enum SupportedChainId {
  ETHEREUM_MAINNET = 1,
  OPTIMISM_MAINNET = 10,
  FLARE_MAINNET = 14,
  BSC_MAINNET = 56,
  POLYGON_MAINNET = 137,
  X1_TESTNET = 195,
  OPBNB_MAINNET = 204,
  FANTOM_MAINNET = 250,
  FANTOM_TESTNET = 4002,
  FANTOM_SONIC = 64165,
  ZKSYNC_TESTNET = 280,
  ZKSYNC_MAINNET = 324,
  HEDERA_MAINNET = 295,
  HEDERA_TESTNET = 296,
  POLYGON_ZKEVM = 1101,
  GANACHE = 1337,
  KAVA_MAINNET = 2222,
  MANTLE_MAINNET = 5000,
  HORIZEN_MAINNET = 7332,
  HAVEN1_DEVNET = 8110,
  BASE_MAINNET = 8453,
  EVMOS_MAINNET = 9001,
  ARTHERA_MAINNET = 10242,
  ARTHERA_TESTNET = 10243,
  HARDHAT = 31337,
  ARBITRUM_MAINNET = 42161,
  CELO_MAINNET = 42220,
  AVALANCHE_MAINNET = 43114,
  LINEA_MAINNET = 59144,
  POLYGON_MUMBAI = 80001,
  BERACHAIN_BARTIO = 80084,
  BLAST_MAINNET = 81457,
  TAIKO_HEKLA = 167009,
  SCROLL_MAINNET = 534352,
  INK_SEPOLIA = 763373,
  SEPOLIA = 11155111,
  BLAST_SEPOLIA = 168587773,
  SKALE_EUROPA = 2046399126,
}

// NOTE: attempting to verify from the cli prgrammatically with npx hardhat verify won't work
// since this config overrides some of the default supported verify networks
// Hence you would verify programmatically with the verify.spec.ts script
export const chainNames: Record<SupportedChainId, string> = {
  [SupportedChainId.ETHEREUM_MAINNET]: "mainnet",
  [SupportedChainId.OPTIMISM_MAINNET]: "optimism-mainnet",
  [SupportedChainId.FLARE_MAINNET]: "flare-mainnet",
  [SupportedChainId.BSC_MAINNET]: "bsc",
  [SupportedChainId.POLYGON_MAINNET]: "polygon-mainnet",
  [SupportedChainId.OPBNB_MAINNET]: "opbnb-mainnet",
  [SupportedChainId.FANTOM_MAINNET]: "fantom-mainnet",
  [SupportedChainId.FANTOM_TESTNET]: "fantom-testnet",
  [SupportedChainId.FANTOM_SONIC]: "fantom-sonic",
  [SupportedChainId.HEDERA_MAINNET]: "hedera-mainnet",
  [SupportedChainId.HEDERA_TESTNET]: "hedera-testnet",
  [SupportedChainId.POLYGON_ZKEVM]: "polygon-zkevm",
  [SupportedChainId.GANACHE]: "ganache",
  [SupportedChainId.MANTLE_MAINNET]: "mantle-mainnet",
  [SupportedChainId.EVMOS_MAINNET]: "evmos-mainnet",
  [SupportedChainId.ARTHERA_MAINNET]: "arthera-mainnet",
  [SupportedChainId.ARTHERA_TESTNET]: "arthera-testnet",
  [SupportedChainId.HARDHAT]: "hardhat",
  [SupportedChainId.AVALANCHE_MAINNET]: "avalanche-mainnet",
  [SupportedChainId.SEPOLIA]: "sepolia",
  [SupportedChainId.ARBITRUM_MAINNET]: "arbitrum-mainnet",
  [SupportedChainId.POLYGON_MUMBAI]: "polygon-mumbai",
  [SupportedChainId.BERACHAIN_BARTIO]: "bartio",
  [SupportedChainId.BLAST_MAINNET]: "blast-mainnet",
  [SupportedChainId.TAIKO_HEKLA]: "taiko-hekla",
  [SupportedChainId.SCROLL_MAINNET]: "scroll-mainnet",
  [SupportedChainId.INK_SEPOLIA]: "ink-sepolia",
  [SupportedChainId.LINEA_MAINNET]: "linea-mainnet",
  [SupportedChainId.HORIZEN_MAINNET]: "horizen-mainnet",
  [SupportedChainId.HAVEN1_DEVNET]: "haven1-devnet",
  [SupportedChainId.BASE_MAINNET]: "base-mainnet",
  [SupportedChainId.ZKSYNC_TESTNET]: "zksync-testnet",
  [SupportedChainId.ZKSYNC_MAINNET]: "zksync-mainnet",
  [SupportedChainId.BLAST_SEPOLIA]: "blast-sepolia",
  [SupportedChainId.X1_TESTNET]: "x1-testnet",
  [SupportedChainId.CELO_MAINNET]: "celo-mainnet",
  [SupportedChainId.KAVA_MAINNET]: "kava-mainnet",
  [SupportedChainId.SKALE_EUROPA]: "skale-europa",
};

const fallbackRpcUrls: Record<SupportedChainId, string[]> = {
  [SupportedChainId.ETHEREUM_MAINNET]: ["https://eth.llamarpc.com"],
  [SupportedChainId.OPTIMISM_MAINNET]: ["https://optimism.llamarpc.com"],
  [SupportedChainId.FLARE_MAINNET]: [
    "https://flare.solidifi.app/ext/C/rpc",
    "https://flare.rpc.thirdweb.com",
    "https://rpc.ankr.com/flare",
    "https://01-gravelines-003-01.rpc.tatum.io/ext/bc/C/rpc",
    "https://flare-api.flare.network/ext/C/rpc",
    "https://01-vinthill-003-02.rpc.tatum.io/ext/bc/C/rpc",
    "https://flare-bundler.etherspot.io",
    "https://rpc.ftso.au/flare",
  ],
  [SupportedChainId.BSC_MAINNET]: [
    "https://bsc-dataseed.bnbchain.org",
    "https://getblock.io/nodes/bsc",
    "https://binance.llamarpc.com",
    "https://rpc.ankr.com/bsc",
    "https://bsc-dataseed1.defibit.io",
    "https://bsc-dataseed1.ninicoin.io",
    "https://bsc-dataseed2.defibit.io",
    "https://bsc-dataseed3.defibit.io",
    "https://bsc-dataseed4.defibit.io",
    "https://bsc-dataseed2.ninicoin.io",
    "https://bsc-dataseed3.ninicoin.io",
    "https://bsc-dataseed4.ninicoin.io",
    "https://bsc-dataseed1.bnbchain.org",
    "https://bsc-dataseed2.bnbchain.org",
    "https://bsc-dataseed3.bnbchain.org",
    "https://bsc-dataseed4.bnbchain.org",
    "https://rpc-bsc.48.club",
    "https://koge-rpc-bsc.48.club",
    "https://endpoints.omniatech.io/v1/bsc/mainnet/public",
    "https://bsc-pokt.nodies.app",
    "https://bsc-mainnet.nodereal.io/v1/64a9df0874fb4a93b9d0a3849de012d3",
    "https://bscrpc.com",
  ],
  [SupportedChainId.POLYGON_MAINNET]: [
    "https://1rpc.io/matic",
    "https://polygon.drpc.org",
    "https://polygon.llamarpc.com",
    "https://polygon.rpc.blxrbdn.com",
    "https://polygon.meowrpc.com",
    "https://gateway.tenderly.co/public/polygon",
    "https://api.tatum.io/v3/blockchain/node/polygon-mainnet",
    "https://rpc-mainnet.matic.quiknode.pro",
    "https://polygon.blockpi.network/v1/rpc/public",
    "https://polygon.gateway.tenderly.co",
    "https://public.stackup.sh/api/v1/node/polygon-mainnet",
    "https://polygon-bor-rpc.publicnode.com",
    "https://polygon-pokt.nodies.app",
  ],
  [SupportedChainId.OPBNB_MAINNET]: ["https://opbnb.publicnode.com"],
  [SupportedChainId.FANTOM_MAINNET]: [
    "https://rpc.fantom.network",
    "https://rpcapi.fantom.network",
    "https://fantom-pokt.nodies.app",
    "https://rpc.ftm.tools",
    "https://rpc.ankr.com/fantom",
    "https://rpc2.fantom.network",
    "https://rpc3.fantom.network",
    "https://fantom-mainnet.public.blastapi.io",
    "https://endpoints.omniatech.io/v1/fantom/mainnet/public",
  ],
  [SupportedChainId.FANTOM_TESTNET]: [
    "https://rpc.testnet.fantom.network",
    "https://endpoints.omniatech.io/v1/fantom/testnet/public",
    "https://rpc.ankr.com/fantom_testnet",
    "https://fantom-testnet.public.blastapi.io",
    "https://fantom-testnet-rpc.publicnode.com",
    "https://fantom.api.onfinality.io/public",
  ],
  [SupportedChainId.FANTOM_SONIC]: ["https://rpc.sonic.fantom.network/"],
  [SupportedChainId.HEDERA_MAINNET]: ["https://mainnet.hashio.io/api"],
  [SupportedChainId.HEDERA_TESTNET]: ["https://testnet.hashio.io/api"],
  [SupportedChainId.POLYGON_ZKEVM]: [
    "https://zkevm-rpc.com",
    "https://rpc.ankr.com/polygon_zkevm",
    "https://1rpc.io/polygon/zkevm",
    "https://polygon-zkevm.drpc.org",
    "https://polygon-zkevm-mainnet.public.blastapi.io",
    "https://polygon-zkevm.blockpi.network/v1/rpc/public",
  ],
  [SupportedChainId.GANACHE]: ["http://localhost:8545"],
  [SupportedChainId.MANTLE_MAINNET]: [
    "https://mantle.drpc.org",
    "https://rpc.mantle.xyz",
    "https://mantle-mainnet.public.blastapi.io",
    "https://mantle.publicnode.com",
    "https://rpc.ankr.com/mantle",
    "https://1rpc.io/mantle",
  ],
  [SupportedChainId.EVMOS_MAINNET]: [
    "https://evmos-evm.publicnode.com",
    "https://evmos.lava.build",
    "https://jsonrpc-evmos.mzonder.com",
    "https://json-rpc.evmos.tcnetwork.io",
    "https://rpc-evm.evmos.dragonstake.io",
    "https://evmos-jsonrpc.alkadeta.com",
    "https://evmos-jsonrpc.stake-town.com",
    "https://evm-rpc.evmos.silentvalidator.com",
    "https://evmos-mainnet.public.blastapi.io",
    "https://jsonrpc-evmos-ia.cosmosia.notional.ventures",
    "https://evmos-jsonrpc.theamsolutions.info",
    "https://alphab.ai/rpc/eth/evmos",
    "https://evmos-json-rpc.0base.dev",
    "https://json-rpc-evmos.mainnet.validatrium.club",
    "https://evmos-json-rpc.stakely.io",
    "https://json-rpc.evmos.blockhunters.org",
    "https://evmos-pokt.nodies.app",
    "https://evmosevm.rpc.stakin-nodes.com",
    "https://evmos-json.antrixy.org",
  ],
  [SupportedChainId.ARTHERA_MAINNET]: ["https://rpc.arthera.net"],
  [SupportedChainId.ARTHERA_TESTNET]: ["https://rpc-test.arthera.net"],
  [SupportedChainId.HARDHAT]: [""],
  [SupportedChainId.AVALANCHE_MAINNET]: [
    "https://avalanche-mainnet-rpc.allthatnode.com",
    "https://rpc.ankr.com/avalanche",
    "https://1rpc.io/avax/c",
    "https://api.avax.network/ext/bc/C/rpc",
    "https://avalanche.public-rpc.com",
    "https://avalanche-c-chain.publicnode.com",
    "https://avalanche.blockpi.network/v1/rpc/public",
    "https://avalanche.drpc.org",
  ],
  [SupportedChainId.SEPOLIA]: ["https://1rpc.io/sepolia"],
  [SupportedChainId.ARBITRUM_MAINNET]: ["https://arbitrum.llamarpc.com"],
  [SupportedChainId.POLYGON_MUMBAI]: ["https://polygon-testnet.public.blastapi.io"],
  [SupportedChainId.BERACHAIN_BARTIO]: [
    "https://bartio.rpc.berachain.com",
    "https://bartio.drpc.org",
    "https://bera-testnet.nodeinfra.com",
    "https://bartio.rpc.b-harvest.io",
  ],
  [SupportedChainId.BLAST_MAINNET]: [
    "https://rpc.blast.io",
    "https://rpc.ankr.com/blast",
    "https://blast.blockpi.network/v1/rpc/public",
    "https://blast.blockpi.network/v1/rpc/public",
    "https://blast.din.dev/rpc",
    "https://blast.gasswap.org",
    "https://blastl2-mainnet.public.blastapi.io",
  ],
  [SupportedChainId.TAIKO_HEKLA]: [
    "https://rpc.ankr.com/taiko_hekla",
    "https://taiko-hekla.blockpi.network/v1/rpc/public",
    "https://rpc.hekla.taiko.xyz",
    "https://hekla.taiko.tools",
  ],
  [SupportedChainId.SCROLL_MAINNET]: [
    "https://rpc.scroll.io",
    "https://scroll.blockpi.network/v1/rpc/public",
    "https://1rpc.io/scroll",
    "https://scroll.drpc.org",
    "https://scroll-mainnet.rpc.grove.city/v1/a7a7c8e2",
    "https://rpc.ankr.com/scroll",
    "https://scroll-mainnet.chainstacklabs.com",
  ],
  [SupportedChainId.INK_SEPOLIA]: [
    "https://rpc-gel-sepolia.inkonchain.com",
  ],
  [SupportedChainId.LINEA_MAINNET]: [
    "https://1rpc.io/linea",
    "https://rpc.linea.build",
    "https://linea.blockpi.network/v1/rpc/public",
    "https://linea.decubate.com",
    "https://linea.drpc.org",
  ],
  [SupportedChainId.HORIZEN_MAINNET]: ["https://rpc.ankr.com/horizen_eon"],
  [SupportedChainId.HAVEN1_DEVNET]: ["https://rpc.staging.haven1.org"],
  [SupportedChainId.BASE_MAINNET]: [
    "https://mainnet.base.org",
    "https://base.blockpi.network/v1/rpc/public",
    "https://1rpc.io/base",
    "https://base-pokt.nodies.app",
    "https://base.meowrpc.com",
    "https://base-mainnet.public.blastapi.io",
    "https://base.gateway.tenderly.co",
    "https://gateway.tenderly.co/public/base",
    "https://rpc.notadegen.com/base",
    "https://base.publicnode.com",
    "https://base.drpc.org",
    "https://endpoints.omniatech.io/v1/base/mainnet/public",
    "https://base.llamarpc.com",
  ],
  [SupportedChainId.ZKSYNC_TESTNET]: ["https://sepolia.era.zksync.dev"],
  [SupportedChainId.ZKSYNC_MAINNET]: [
    "https://mainnet.era.zksync.io",
    "https://1rpc.io/zksync2-era",
    "https://zksync-era.blockpi.network/v1/rpc/public",
    "https://zksync.meowrpc.com",
  ],
  [SupportedChainId.BLAST_SEPOLIA]: ["https://sepolia.blast.io"],
  [SupportedChainId.X1_TESTNET]: ["https://x1testrpc.okx.com", "https://x1-testnet.blockpi.network/v1/rpc/public"],
  [SupportedChainId.CELO_MAINNET]: ["https://forno.celo.org", "https://rpc.ankr.com/celo", "https://1rpc.io/celo"],
  [SupportedChainId.KAVA_MAINNET]: [
    "https://evm.kava.io",
    "https://rpc.ankr.com/kava_evm",
    "https://kava.api.onfinality.io/public",
    "https://kava-evm-rpc.publicnode.com",
    "https://kava-pokt.nodies.app",
    "https://evm.kava.chainstacklabs.com",
    "https://evm.kava-rpc.com",
  ],
  [SupportedChainId.SKALE_EUROPA]: ["https://mainnet.skalenodes.com/v1/elated-tan-skat"],
};

export const defaultRpcUrls: Record<SupportedChainId, string> = {
  [SupportedChainId.ETHEREUM_MAINNET]: fallbackRpcUrls[SupportedChainId.ETHEREUM_MAINNET][0],
  [SupportedChainId.OPTIMISM_MAINNET]: fallbackRpcUrls[SupportedChainId.OPTIMISM_MAINNET][0],
  [SupportedChainId.FLARE_MAINNET]: fallbackRpcUrls[SupportedChainId.FLARE_MAINNET][0],
  [SupportedChainId.BSC_MAINNET]: fallbackRpcUrls[SupportedChainId.BSC_MAINNET][0],
  [SupportedChainId.POLYGON_MAINNET]: fallbackRpcUrls[SupportedChainId.POLYGON_MAINNET][0],
  [SupportedChainId.OPBNB_MAINNET]: fallbackRpcUrls[SupportedChainId.OPBNB_MAINNET][0],
  [SupportedChainId.FANTOM_MAINNET]: fallbackRpcUrls[SupportedChainId.FANTOM_MAINNET][0],
  [SupportedChainId.FANTOM_TESTNET]: fallbackRpcUrls[SupportedChainId.FANTOM_TESTNET][0],
  [SupportedChainId.FANTOM_SONIC]: fallbackRpcUrls[SupportedChainId.FANTOM_SONIC][0],
  [SupportedChainId.HEDERA_MAINNET]: fallbackRpcUrls[SupportedChainId.HEDERA_MAINNET][0],
  [SupportedChainId.HEDERA_TESTNET]: fallbackRpcUrls[SupportedChainId.HEDERA_TESTNET][0],
  [SupportedChainId.POLYGON_ZKEVM]: fallbackRpcUrls[SupportedChainId.POLYGON_ZKEVM][0],
  [SupportedChainId.GANACHE]: fallbackRpcUrls[SupportedChainId.GANACHE][0],
  [SupportedChainId.MANTLE_MAINNET]: fallbackRpcUrls[SupportedChainId.MANTLE_MAINNET][0],
  [SupportedChainId.EVMOS_MAINNET]: fallbackRpcUrls[SupportedChainId.EVMOS_MAINNET][0],
  [SupportedChainId.ARTHERA_MAINNET]: fallbackRpcUrls[SupportedChainId.ARTHERA_MAINNET][0],
  [SupportedChainId.ARTHERA_TESTNET]: fallbackRpcUrls[SupportedChainId.ARTHERA_TESTNET][0],
  [SupportedChainId.HARDHAT]: fallbackRpcUrls[SupportedChainId.HARDHAT][0],
  [SupportedChainId.AVALANCHE_MAINNET]: fallbackRpcUrls[SupportedChainId.AVALANCHE_MAINNET][0],
  [SupportedChainId.SEPOLIA]: fallbackRpcUrls[SupportedChainId.SEPOLIA][0],
  [SupportedChainId.ARBITRUM_MAINNET]: fallbackRpcUrls[SupportedChainId.ARBITRUM_MAINNET][0],
  [SupportedChainId.POLYGON_MUMBAI]: fallbackRpcUrls[SupportedChainId.POLYGON_MUMBAI][0],
  [SupportedChainId.BERACHAIN_BARTIO]: fallbackRpcUrls[SupportedChainId.BERACHAIN_BARTIO][0],
  [SupportedChainId.BLAST_MAINNET]: fallbackRpcUrls[SupportedChainId.BLAST_MAINNET][0],
  [SupportedChainId.TAIKO_HEKLA]: fallbackRpcUrls[SupportedChainId.TAIKO_HEKLA][0],
  [SupportedChainId.SCROLL_MAINNET]: fallbackRpcUrls[SupportedChainId.SCROLL_MAINNET][0],
  [SupportedChainId.INK_SEPOLIA]: fallbackRpcUrls[SupportedChainId.INK_SEPOLIA][0],
  [SupportedChainId.LINEA_MAINNET]: fallbackRpcUrls[SupportedChainId.LINEA_MAINNET][0],
  [SupportedChainId.HORIZEN_MAINNET]: fallbackRpcUrls[SupportedChainId.HORIZEN_MAINNET][0],
  [SupportedChainId.BASE_MAINNET]: fallbackRpcUrls[SupportedChainId.BASE_MAINNET][0],
  [SupportedChainId.HAVEN1_DEVNET]: fallbackRpcUrls[SupportedChainId.HAVEN1_DEVNET][0],
  [SupportedChainId.ZKSYNC_TESTNET]: fallbackRpcUrls[SupportedChainId.ZKSYNC_TESTNET][0],
  [SupportedChainId.ZKSYNC_MAINNET]: fallbackRpcUrls[SupportedChainId.ZKSYNC_MAINNET][0],
  [SupportedChainId.BLAST_SEPOLIA]: fallbackRpcUrls[SupportedChainId.BLAST_SEPOLIA][0],
  [SupportedChainId.X1_TESTNET]: fallbackRpcUrls[SupportedChainId.X1_TESTNET][0],
  [SupportedChainId.CELO_MAINNET]: fallbackRpcUrls[SupportedChainId.CELO_MAINNET][0],
  [SupportedChainId.KAVA_MAINNET]: fallbackRpcUrls[SupportedChainId.KAVA_MAINNET][0],
  [SupportedChainId.SKALE_EUROPA]: fallbackRpcUrls[SupportedChainId.SKALE_EUROPA][0],
};

export const infuraSupportedNetworks: Partial<Record<SupportedChainId, boolean>> = {
  [SupportedChainId.ETHEREUM_MAINNET]: true,
  [SupportedChainId.BASE_MAINNET]: false,
  [SupportedChainId.POLYGON_MAINNET]: true,
  [SupportedChainId.OPTIMISM_MAINNET]: true,
  [SupportedChainId.ARBITRUM_MAINNET]: true,
  [SupportedChainId.AVALANCHE_MAINNET]: true,
};
